# Generated by Django 4.2.4 on 2023-08-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='important',
            new_name='importante',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='titulo',
        ),
    ]
